
INSERT INTO tb_category(name) VALUES ('Jogos');
INSERT INTO tb_category(name) VALUES ('Filmes');
INSERT INTO tb_category(name) VALUES ('Livros');

INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 1 Remastered', 'Jogo refeito especialmente para os fãns da franquia', 300.00, 'http://img.com');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 2 Remake', 'Resident Evil 2 Remake é uma versão refeita de 2019 do clássico game de terror Resident Evil 2 da Capcom, lançado originalmente no PlayStation One em 1998. O game é a sequência do primeiro jogo da franquia, sendo protagonizado pela dupla Claire Redfield e Leon S. Kennedy durante um apocalipse zumbi na cidade de Raccoon City, causado pelo T-Virus da corporação Umbrella. ', 350.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 3 Remake', 'O Resident Evil 3 Remake, lançado em 2020 pela Capcom, é uma reimaginação moderna do clássico de 1999. No jogo, acompanhamos Jill Valentine, uma ex-integrante da S.T.A.R.S., enquanto ela tenta escapar de Raccoon City durante o surto de zumbis causado pelo T-Virus, enfrentando o implacável vilão Nemesis. A história ocorre paralelamente aos eventos de Resident Evil 2, oferecendo uma perspectiva única sobre o caos na cidade.' , 250.00, 'http...');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 4 Remake', 'O Resident Evil 4 Remake revitaliza o clássico de 2005 com gráficos e mecânicas modernas, mantendo a icônica história de Leon S. Kennedy em uma vila infestada por infectados. O jogo combina elementos de horror e ação com melhorias no combate, permitindo maior mobilidade e uso estratégico do ambiente. A ambientação e os personagens estão mais sombrios e detalhados, aumentando a imersão e o clima de tensão. É um remake que respeita o original, mas traz frescor e intensidade para veteranos e novos jogadores.' , 450.00, 'http...');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 5' , 'Resident Evil 5, lançado em 2009, marca uma mudança significativa na série ao priorizar a ação em vez do terror, introduzindo a jogabilidade cooperativa como destaque. No jogo, Chris Redfield e sua nova parceira, Sheva Alomar, enfrentam uma epidemia de Las Plagas na África, onde inimigos infectados são mais ágeis e organizados. A história expande o universo de Resident Evil, revelando mais sobre a corporação Tricell e os planos de Albert Wesker. Com gráficos marcantes para a época e uma mecânica de combate mais voltada para tiroteios intensos, Resident Evil 5 foi bem recebido por seu modo cooperativo, mas também foi criticado por se afastar do clima de horror que caracteriza a série. Apesar disso, o jogo é um marco por redefinir a franquia e atrair uma nova base de fãs com sua ação frenética e enredo envolvente.' , 150.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 6' ,'Resident Evil 6, lançado em 2012, é um dos jogos mais ambiciosos da série, oferecendo quatro campanhas interligadas e uma narrativa global onde diferentes personagens, como Leon S. Kennedy, Chris Redfield, Jake Muller e Ada Wong, enfrentam uma nova ameaça bioterrorista. O jogo explora múltiplos estilos de gameplay, misturando ação intensa, cenas cinematográficas e elementos de terror, com cada campanha refletindo o estilo e as habilidades dos personagens.' , 150.00, 'http...');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 7' , 'Resident Evil 7: Biohazard, lançado em 2017, marca um retorno ao horror de sobrevivência, renovando a franquia com uma perspectiva em primeira pessoa e um foco em atmosfera e tensão. No papel de Ethan Winters, os jogadores exploram a sombria propriedade da família Baker na Louisiana enquanto buscam sua esposa desaparecida, Mia. Com ambientes claustrofóbicos e um estilo mais voltado para o horror psicológico, o jogo foi aclamado por resgatar o clima de terror da série original, oferecendo uma experiência mais lenta e imersiva. A introdução da RE Engine permitiu gráficos detalhados, intensificando o horror visual e redefinindo o caminho da franquia para o futuro.' , 250.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 8' , 'Já Resident Evil Village, o oitavo título principal, lançado em 2021, continua a jornada de Ethan Winters, agora em uma vila remota na Europa onde ele busca resgatar sua filha. Com um equilíbrio entre o horror de sobrevivência e elementos de ação, o jogo expande o universo introduzindo novos personagens icônicos, como Lady Dimitrescu e Heisenberg, e criaturas sobrenaturais, como lobisomens e vampiros. A ambientação variada e um design mais expansivo mesclam os estilos de Resident Evil 4 e Resident Evil 7, oferecendo uma experiência mais dinâmica e menos linear. Com gráficos impressionantes e uma narrativa envolvente, Resident Evil Village foi elogiado por sua inovação e pela capacidade de manter o horror enquanto amplia o escopo de gameplay.', 350.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 2 Original 1998', 'Resident Evil 2, lançado em 1998, é considerado um marco no gênero de survival horror e consolidou o sucesso da franquia. A história acompanha Leon S. Kennedy, um policial novato, e Claire Redfield, em busca de seu irmão Chris, enquanto tentam escapar de Raccoon City, tomada por uma infestação de zumbis causada pelo T-Virus da Umbrella Corporation. O jogo trouxe inovações como as campanhas paralelas de Leon e Claire, que oferecem diferentes perspectivas e desafios, introduzindo mecânicas como o zapping system, que altera eventos conforme o progresso de cada personagem. Com gráficos avançados para a época, ambientes claustrofóbicos e uma atmosfera de terror intenso, Resident Evil 2 é até hoje lembrado como um dos melhores jogos da série e do gênero.' , 800.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident evil 3 Original 1999', 'Resident Evil 3: Nemesis, lançado em 1999, aprofunda o caos em Raccoon City enquanto a protagonista Jill Valentine tenta sobreviver à epidemia de T-Virus. O diferencial deste jogo é a introdução do vilão implacável Nemesis, uma arma biológica programada para caçar membros da S.T.A.R.S., que persegue Jill ao longo do jogo, aumentando a tensão. Com mecânicas como a esquiva e o sistema de criação de munição, Resident Evil 3 trouxe mais ação e recursos estratégicos ao gameplay, diferenciando-se dos dois primeiros jogos. Apesar de ser mais curto, o jogo foi elogiado por seu ritmo acelerado e pela presença constante de Nemesis, que criava uma sensação de perigo constante, tornando-o um clássico querido pelos fãs da série.', 1200.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: O Hóspede Maldito', 'Alice e uma equipe tática invadem o laboratório da Umbrella Corporation, a Colmeia, para conter um surto de T-Virus que transforma humanos em zumbis. Enfrentam zumbis e o sistema de segurança mortal.', 50.00, 'http...');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: Apocalipse', 'Após escapar da Colmeia, Alice descobre que Raccoon City foi tomada pelo vírus. Com a ajuda de outros sobreviventes, luta para escapar enquanto é perseguida pela arma biológica Nemesis.', 80.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: A Extinção', 'Em um mundo pós-apocalíptico, Alice se junta a um grupo de sobreviventes no deserto e descobre que a Umbrella ainda busca usá-la para desenvolver uma cura para o vírus.', 40.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: Recomeço' , 'Alice busca refúgio em Los Angeles, mas descobre que a Umbrella controla a cidade. Enfrenta novos monstros e aliados na luta para derrubar a corporação de vez.', 75.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: Retribuição' , 'Capturada pela Umbrella, Alice acorda em uma instalação onde enfrenta simulações de diferentes surtos virais e reencontra antigos aliados e inimigos.', 50.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: O Capítulo Final' , 'Alice retorna a Raccoon City para destruir a Umbrella e salvar a humanidade no que parece ser a última batalha contra a corporação e suas armas biológicas.', 80.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: Bem-Vindo a Raccoon City (reboot)', 'Resident Evil: Bem-Vindo a Raccoon City (2021) é um reboot da franquia de filmes, com foco mais fiel aos jogos originais. O filme adapta os eventos de Resident Evil 1 e Resident Evil 2, com Raccoon City em colapso devido à proliferação do T-Virus, criado pela Umbrella Corporation. A história segue Claire Redfield e Leon S. Kennedy enquanto tentam sobreviver ao ataque dos zumbis e descobrir os segredos sombrios da corporação. Ao mesmo tempo, Jill Valentine e Chris Redfield se unem para enfrentar ameaças biológicas, incluindo o implacável Nemesis.', 150.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil 6: Código: Verônica', 'Baseado no jogo Resident Evil Code: Veronica, este livro segue Claire Redfield, que após escapar de Raccoon City, continua sua busca por seu irmão, Chris Redfield. Claire é capturada e levada para uma ilha remota controlada pela Umbrella, onde ela descobre segredos obscuros sobre a corporação. Durante a história, ela enfrenta os horrores do vírus, monstros mutantes e os perigos do novo inimigo, Alfred Ashford, um membro da família Ashford, que controla a ilha. O livro expande o enredo do jogo, com mais detalhes sobre os eventos e personagens.', 120.00, 'http..');
INSERT INTO tb_product(name, description, price, img_url) VALUES ('Resident Evil: Caliban Cove', 'Caliban Cove se passa após os eventos do primeiro jogo de Resident Evil. O livro segue os protagonistas Jill Valentine e o ex-policial Brad Vickers, que se unem para investigar um laboratório secreto da Umbrella em uma ilha isolada. Eles descobrem uma nova experiência de vírus, que resulta em monstros ainda mais perigosos. A história oferece uma narrativa mais profunda e detalhada sobre a Umbrella e seus experimentos, com muita ação, suspense e mistério enquanto Jill e Brad tentam escapar e impedir a propagação do vírus.', 150.00, 'http..');

INSERT INTO tb_product_category (product_id, category_id) VALUES (1, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (2, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (3, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (4, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (5, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (6, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (7, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (8, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (9, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (10, 1);
INSERT INTO tb_product_category (product_id, category_id) VALUES (11, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (12, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (13, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (14, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (15, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (16, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (17, 2);
INSERT INTO tb_product_category (product_id, category_id) VALUES (18, 3);
INSERT INTO tb_product_category (product_id, category_id) VALUES (19, 3);

INSERT INTO tb_user (name, email, phone, birth_date, password) VALUES ('Wellington Rodrigues', 'wellington@gmail.com', '6299999-6666', '2000-12-15', '123456');
INSERT INTO tb_user (name, email, phone, birth_date, password) VALUES ('Larissa Costa Silva', 'larissa@outlook.com', '6298888-4444', '1998-08-12', '123456');
INSERT INTO tb_user (name, email, phone, birth_date, password) VALUES ('Cleiton dos Santos', 'cleiton.santos@gmail.com', '6292222-5555', '1990-05-30', '123456');

INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-04-20T18:00:00Z', 0, 2);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-06-18T20:00:00Z', 3, 1);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-07-21T14:00:00Z', 4, 3);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-03-06T17:00:00Z', 2, 2);
INSERT INTO tb_order (moment, status, client_id) VALUES (TIMESTAMP WITH TIME ZONE '2024-02-05T08:00:00Z', 1, 1);

INSERT INTO tb_orderitem (order_id, product_id, quantity, price) VALUES (1, 1, 1, 300.00);
INSERT INTO tb_orderitem (order_id, product_id, quantity, price) VALUES (3, 4, 2, 450.00);
INSERT INTO tb_orderitem (order_id, product_id, quantity, price) VALUES (5, 18, 1, 120.00);
INSERT INTO tb_orderitem (order_id, product_id, quantity, price) VALUES (2, 2, 4, 350.00);
INSERT INTO tb_orderitem (order_id, product_id, quantity, price) VALUES (4, 11, 1, 50.00);

INSERT INTO tb_payment (order_id, moment) VALUES (3, TIMESTAMP WITH TIME ZONE '2024-06-19T20:00:00Z');
INSERT INTO tb_payment (order_id, moment) VALUES (1, TIMESTAMP WITH TIME ZONE '2024-02-06T14:00:00Z');
INSERT INTO tb_payment (order_id, moment) VALUES (4, TIMESTAMP WITH TIME ZONE '2024-07-15T12:00:00Z');